# Generated by Django 6.0 on 2026-01-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Менеджер может отключить рассылку. Отключённая рассылка не отправляется.",
                verbose_name="Активна",
            ),
        ),
    ]
