# Generated by Django 6.0 on 2026-01-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailing_is_enabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["start_time"],
                "permissions": [("can_disable_mailing", "Может отключать рассылки")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
